obstacle_range: 4.5 #2.5
raytrace_range: 5.5 #3.0
#footprint: [[x0, y0], [x1, y1], ... [xn, yn]]
robot_radius: 0.75 #0.45
inflation_radius: 0.95

observation_sources: laser_scan_sensor 
# observation_sources: point_cloud_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: scan, marking: true, clearing: true}
# laser_scan_sensor: {sensor_frame: iris_demo/left_camera_optical_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}
# point_cloud_sensor_sensor: {sensor_frame: iris_demo/left_camera_optical_frame, data_type: PointCloud2, topic: /iris_demo/ZED_stereocamera/camera/points2, marking: true, clearing: true}
